[package]
name = "beaver-cli"
version = "5.0.0"
edition.workspace = true
authors.workspace = true

[dependencies]
clap = { workspace = true, features = ["cargo"] }
lazy_static = { workspace = true }
beaver = { path = "../beaver" }

[build-dependencies]
const-gen = "1.6"
rb-sys-env = "0.2"
