[package]
name = "spm-manifest"
edition.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
utils = { path = "../utils", features = ["junctions"] }

[dev-dependencies]
tempdir = { workspace = true }
