[package]
name = "glob"
edition.workspace = true
authors.workspace = true

[dependencies]
utils = { path = "../utils", features = ["junctions"] }
unicode-segmentation = { workspace = true }
regex = { workspace = true }
thiserror = { workspace = true }
