name: Test macOS

on:
  push:
    branches: [master]

# TODO: test on multiple Ruby versions (matrix)
# Build with ruby-build
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - full: "3.1.6"
            short: "3.1"
          - full: "3.2.6"
            short: "3.2"
          - full: "3.3.6"
            short: "3.3"
          - full: "3.4.1"
            short: "3.4"
    name: Build and test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: SwiftyLab/setup-swift@latest
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install ruby-build
        run: brew install ruby-build chruby
      - name: ruby-build versions
        run: ruby-build -l
      # Install the specified ruby version and set up PKG_CONFIG_PATH to point to the correct directory
      - name: Install ruby
        run: |
          ruby-build -d ${{ matrix.ruby-version.full }} ~/.rubies
          echo "PKG_CONVIG_PATH=${PKG_CONFIG_PATH:${PKG_CONFIG_PATH}:}$(realpath ~/.rubies/${{ matrix.ruby-version.full }}/lib/pkgconfig)" >> $GITHUB_ENV

      # - name: Available ruby versions
      #   run: chruby
      - name: Swift Version
        run: swift --version
      - name: Ruby Version
        run: ruby --version
      - name: Rust Version
        run: |
          rustc --version
          cargo --version

      - name: Configure
        run: ruby configure.rb pkgconfig ${{ matrix.ruby-version.short }}
      - name: Build
        run: ruby build.rb
      - name: Test
        run: ruby build.rb test
