name: Test Windows

on:
  push:
    branches: [master]

jobs:
  test:
    name: Build and test
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Swift Version
        run: swift --version

      - name: Build
        run: swift build
      - name: Test
        run: swift test
