name: Test macOS

on:
  push:
    branches: [master]

jobs:
  test:
    name: Build and test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.9'
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: false
    - name: setup minitest
      run: gem install minitest
    - name: Build
      run: zsh build.sh build install
    - name: check for native extension errors
      run: cat  /Users/runner/hostedtoolcache/Ruby/*/x64/lib/ruby/gems/*/extensions/*/*/msgpack-*/mkmf.log
    - name: Run tests
      run: zsh build.sh test-workflow

