name: Test Linux

on:
  push:
    branches: [master]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Swift Version
        run: swift --version
      - name: Ruby Version
        run: ruby --version
      - name: Rust Version
        run: |
          rustc --version
          cargo --version

      - name: Configure
        run: ruby configure.rb
      - name: Build
        run: ruby build.rb
      - name: Test
        run: ruby build.rb test
