name: Test macOS

on:
  push:
    branches: [master]

jobs:
  test:
    name: Build and test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: SwiftyLab/setup-swift@latest
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install ruby 3
        run: brew install ruby

      - name: Swift Version
        run: swift --version
      - name: Ruby Version
        run: ruby --version
      - name: Rust Version
        run: |
          rustc --version
          cargo --version

      - name: Configure
        run: ruby configure.rb
      - name: Build
        run: ruby build.rb
      - name: Test
        run: ruby build.rb test
