name: Test Windows

on:
  push:
    branches: [master]

jobs:
  test:
    name: Build and test
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set Swift bin env var
        run: |
          set PATH="%PATH%;C:\Swift\bin"
          setx /M PATH "%PATH%;C:\Swift\bin"

      - name: Swift Version
        run: swift --version
      - name: Ruby Version
        run: ruby --version
      - name: Rust Version
        run: |
          rustc --version
          cargo --version

      - name: Build
        run: ruby build.rb
      - name: Test
        run: ruby build.rb test
